# Retry deployment with new key without passphrase
name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: 143.110.224.182
          username: brainjelli
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            echo "Navigating to BrainMaze directory"
            cd ~/BrainMaze || { echo "Directory ~/BrainMaze not found"; exit 1; }
            echo "Pulling latest changes"
            git reset --hard
            git pull origin main || { echo "git pull failed"; exit 1; }
            echo "Reloading Nginx"
            sudo systemctl reload nginx || { echo "Nginx reload failed"; exit 1; }
            echo "Deployment successful"
