name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: 64.227.98.6
          username: brainjelli
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/BrainMaze
            git pull origin main
            sudo systemctl reload nginx
