name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh

      - name: Deploy to Droplet
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key brainjelli@$DROPLET_IP << 'ENDSSH'
            mkdir -p /home/brainjelli/BrainMaze
            rm -rf /home/brainjelli/BrainMaze/*
          ENDSSH
          scp -o StrictHostKeyChecking=no -i /tmp/ssh_key -r ./* brainjelli@$DROPLET_IP:/home/brainjelli/BrainMaze/
          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key brainjelli@$DROPLET_IP << 'ENDSSH'
            cd /home/brainjelli/BrainMaze
            sudo chown -R brainjelli:brainjelli /home/brainjelli/BrainMaze
            sudo chmod -R 644 /home/brainjelli/BrainMaze/*
            sudo chmod -R 755 /home/brainjelli/BrainMaze
            npm install
            pm2 restart brainjelli-backend || pm2 start backend/server.js --name brainjelli-backend
            sudo systemctl reload nginx
          ENDSSH
          rm /tmp/ssh_key
