name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Droplet
        env:
          DROPLET_IP: 143.110.224.182
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh
          echo "$SSH_PRIVATE_KEY" > REDACTED
          chmod 600 REDACTED
          ssh -o StrictHostKeyChecking=no -i REDACTED brainjelli@$DROPLET_IP << 'ENDSSH'
            mkdir -p /home/brainjelli/BrainMaze
            rm -rf /home/brainjelli/BrainMaze/*
            exit
          ENDSSH
          scp -o StrictHostKeyChecking=no -i REDACTED -r ./* brainjelli@$DROPLET_IP:/home/brainjelli/BrainMaze/
          ssh -o StrictHostKeyChecking=no -i REDACTED brainjelli@$DROPLET_IP << 'ENDSSH'
            sudo chown -R brainjelli:brainjelli /home/brainjelli/BrainMaze
            sudo chmod -R 644 /home/brainjelli/BrainMaze/*
            sudo chmod -R 755 /home/brainjelli/BrainMaze
            exit
          ENDSSH
          rm REDACTED