- name: Test Push
  env:
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    DROPLET_IP: ${{ secrets.DROPLET_IP }}
  run: |
    echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key
    chmod 600 /tmp/ssh_key
    ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key brainjelli@$DROPLET_IP 'echo "Test connection successful"'
    rm /tmp/ssh_key
