name: Test Push Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log commit message
        run: echo "Received commit with message ${{ github.event.head_commit.message }}"
